import flask.cli
from flask import Flask, request, jsonify, Response, stream_with_context
from flask_cors import CORS





"""
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
ai4water                  1.6                      pypi_0    pypi
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
akshare                   1.15.46                  pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
albucore                  0.0.17                   pypi_0    pypi
albumentations            1.4.18                   pypi_0    pypi
alembic                   1.13.3                   pypi_0    pypi
alpha-vantage             3.0.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.2.0            py38haa95532_0    defaults
apptools                  5.3.0                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0    defaults
array-record              0.4.0                    pypi_0    pypi
asgiref                   3.8.1            py38haa95532_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
astunparse                1.6.3                    pypi_0    pypi
async-lru                 2.0.4            py38haa95532_0    defaults
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.15.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.1                pyhd3eb1b0_1    defaults
backports.zoneinfo        0.2.1            py38h2bbff1b_0    defaults
bayesian-optimization     1.4.3                    pypi_0    pypi
bayesianoptimization      0.0.0                    pypi_0    pypi
beautifulsoup4            4.12.3           py38haa95532_0    defaults
bleach                    6.1.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
brotli-python             1.0.9            py38hd77b12b_8    defaults
ca-certificates           2024.7.2             haa95532_0    defaults
cachetools                5.3.3                    pypi_0    pypi
catboost                  1.2.5                    pypi_0    pypi
certifi                   2024.7.4         py38haa95532_0    defaults
cffi                      1.16.0           py38h2bbff1b_1    defaults
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
colorama                  0.4.6            py38haa95532_0    defaults
colorlog                  6.8.2                    pypi_0    pypi
comm                      0.2.1            py38haa95532_0    defaults
contourpy                 1.1.1                    pypi_0    pypi
coreforecast              0.0.12                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
deap                      1.4.1                    pypi_0    pypi
debugpy                   1.6.7            py38hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
distlib                   0.3.8                    pypi_0    pypi
django                    4.2.15                   pypi_0    pypi
djangorestframework       3.15.2                   pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
docutils                  0.20.1                   pypi_0    pypi
easy-mpl                  0.21.4                   pypi_0    pypi
envisage                  7.0.3                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
etils                     1.3.0                    pypi_0    pypi
eval-type-backport        0.2.2                    pypi_0    pypi
exceptiongroup            1.2.0            py38haa95532_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
fastjsonschema            2.20.0                   pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
flask-cors                5.0.0                    pypi_0    pypi
flatbuffers               2.0.7                    pypi_0    pypi
fonttools                 4.53.0                   pypi_0    pypi
frozendict                2.4.6                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.0                 pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               2.30.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.65.0                   pypi_0    pypi
greenlet                  3.1.1                    pypi_0    pypi
grpcio                    1.64.1                   pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
huggingface-hub           0.25.1                   pypi_0    pypi
icu                       73.1                 h6c2663c_0    defaults
idna                      3.7              py38haa95532_0    defaults
imageio                   2.35.1                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        7.2.1                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
importlib_metadata        7.0.1                hd3eb1b0_0    defaults
importlib_resources       6.1.1            py38haa95532_1    defaults
intel-openmp              2021.4.0                 pypi_0    pypi
ipykernel                 6.28.0           py38haa95532_0    defaults
ipython                   8.12.2           py38haa95532_0    defaults
ipywidgets                8.1.2            py38haa95532_0    defaults
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.18.1           py38haa95532_1    defaults
jinja2                    3.1.5                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonpath                  0.82.2                   pypi_0    pypi
jsonschema                4.22.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter                   1.0.0            py38haa95532_9    defaults
jupyter-client            8.6.2                    pypi_0    pypi
jupyter-lsp               2.2.0            py38haa95532_0    defaults
jupyter_client            8.6.0            py38haa95532_0    defaults
jupyter_console           6.6.3            py38haa95532_0    defaults
jupyter_core              5.7.2            py38haa95532_0    defaults
jupyter_events            0.10.0           py38haa95532_0    defaults
jupyter_server            2.14.1           py38haa95532_0    defaults
jupyter_server_terminals  0.4.4            py38haa95532_1    defaults
jupyterlab                4.0.11           py38haa95532_0    defaults
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.25.1           py38haa95532_0    defaults
jupyterlab_widgets        3.0.10           py38haa95532_0    defaults
keras                     2.7.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keras-self-attention      0.51.0                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h5b6d351_1    defaults
lazy-loader               0.4                      pypi_0    pypi
libclang                  18.1.1                   pypi_0    pypi
libclang13                14.0.6          default_h8e68704_1    defaults
libpng                    1.6.39               h8cc25b3_0    defaults
libpq                     12.15                hb652d5d_1    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
lightgbm                  4.4.0                    pypi_0    pypi
lightning-utilities       0.11.7                   pypi_0    pypi
llvmlite                  0.41.1                   pypi_0    pypi
lxml                      5.3.0                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_1    defaults
mako                      1.3.5                    pypi_0    pypi
markdown                  3.6                      pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
matplotlib-inline         0.1.6            py38haa95532_0    defaults
mayavi                    4.8.2                    pypi_0    pypi
mini-racer                0.12.4                   pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mkl                       2021.4.0                 pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
multitasking              0.0.11                   pypi_0    pypi
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.4                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
nbsphinx                  0.9.4                    pypi_0    pypi
nest-asyncio              1.6.0            py38haa95532_0    defaults
networkx                  3.1                      pypi_0    pypi
neuralforecast            1.7.5                    pypi_0    pypi
notebook                  7.0.8            py38haa95532_1    defaults
notebook-shim             0.2.3            py38haa95532_0    defaults
numba                     0.58.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.11.0.86                pypi_0    pypi
openpyxl                  3.1.5                    pypi_0    pypi
openssl                   1.1.1w               h2bbff1b_0    defaults
opt-einsum                3.3.0                    pypi_0    pypi
optuna                    4.0.0                    pypi_0    pypi
overrides                 7.4.0            py38haa95532_0    defaults
packaging                 24.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pandas-datareader         0.10.0                   pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    defaults
patsy                     0.5.6                    pypi_0    pypi
peewee                    3.17.8                   pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0             py38haa95532_0    defaults
pipenv                    2024.0.1                 pypi_0    pypi
pkgutil-resolve-name      1.3.10           py38haa95532_1    defaults
platformdirs              4.2.2                    pypi_0    pypi
plotly                    5.22.0                   pypi_0    pypi
ply                       3.11                     py38_0    defaults
prettytable               3.10.0                   pypi_0    pypi
prometheus_client         0.14.1           py38haa95532_0    defaults
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.43           py38haa95532_0    defaults
prompt_toolkit            3.0.43               hd3eb1b0_0    defaults
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.0            py38h2bbff1b_0    defaults
pulp                      2.9.0                    pypi_0    pypi
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
pyaml                     24.4.0                   pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pyasn1                    0.6.0                    pypi_0    pypi
pyasn1-modules            0.4.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydantic                  2.10.6                   pypi_0    pypi
pydantic-core             2.27.2                   pypi_0    pypi
pyecharts                 2.0.6                    pypi_0    pypi
pyface                    8.0.0                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pymysql                   1.1.1                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyqt                      5.15.10          py38hd77b12b_0    defaults
pyqt5-sip                 12.13.0          py38h2bbff1b_0    defaults
pysocks                   1.7.1            py38haa95532_0    defaults
python                    3.8.13               h6244533_1    defaults
python-dateutil           2.9.0post0       py38haa95532_2    defaults
python-fastjsonschema     2.16.2           py38haa95532_0    defaults
python-json-logger        2.0.7            py38haa95532_0    defaults
python-tzdata             2023.3             pyhd3eb1b0_0    defaults
pytorch-lightning         2.4.0                    pypi_0    pypi
pytz                      2024.1           py38haa95532_0    defaults
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pywinpty                  2.0.10           py38h5da7b33_0    defaults
pyyaml                    6.0.1            py38h2bbff1b_0    defaults
pyzmq                     26.0.3                   pypi_0    pypi
qt-main                   5.15.2              he2df7e6_10    defaults
qtconsole                 5.5.1            py38haa95532_0    defaults
qtpy                      2.4.1            py38haa95532_0    defaults
ray                       2.10.0                   pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
regex                     2024.9.11                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
rfc3339-validator         0.1.4            py38haa95532_0    defaults
rfc3986-validator         0.1.1            py38haa95532_0    defaults
rpds-py                   0.18.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scikit-optimize           0.10.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.2            py38haa95532_0    defaults
seqmetrics                1.3.4                    pypi_0    pypi
setuptools                69.5.1           py38haa95532_0    defaults
shap                      0.44.1                   pypi_0    pypi
simpleitk                 2.4.1                    pypi_0    pypi
simplejson                3.19.2                   pypi_0    pypi
sip                       6.7.12           py38hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
slicer                    0.0.7                    pypi_0    pypi
sniffio                   1.3.0            py38haa95532_0    defaults
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.5              py38haa95532_0    defaults
sphinx                    7.1.2                    pypi_0    pypi
sphinx-copybutton         0.5.2                    pypi_0    pypi
sphinx-gallery            0.16.0                   pypi_0    pypi
sphinx-issues             4.1.0                    pypi_0    pypi
sphinx-prompt             1.7.0                    pypi_0    pypi
sphinx-rtd-theme          2.0.0                    pypi_0    pypi
sphinx-toggleprompt       0.2.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jquery      4.1                      pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                2.0.35                   pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    defaults
sqlparse                  0.5.1                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0    defaults
statsmodels               0.14.1                   pypi_0    pypi
sympy                     1.12.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.13.0                pypi_0    pypi
tenacity                  8.4.2                    pypi_0    pypi
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
tensorflow                2.7.0                    pypi_0    pypi
tensorflow-datasets       4.9.2                    pypi_0    pypi
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
tensorflow-metadata       1.14.0                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
terminado                 0.17.1           py38haa95532_0    defaults
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tinycss2                  1.3.0                    pypi_0    pypi
tokenizers                0.19.1                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1            py38haa95532_0    defaults
torch                     2.4.1                    pypi_0    pypi
torchmetrics              1.4.2                    pypi_0    pypi
torchvision               0.19.1                   pypi_0    pypi
tornado                   6.4.1            py38h827c3e9_0    defaults
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3           py38haa95532_0    defaults
traits                    6.4.3                    pypi_0    pypi
traitsui                  8.0.0                    pypi_0    pypi
transformers              4.44.2                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2            py38haa95532_0    defaults
utilsforecast             0.2.5                    pypi_0    pypi
vc                        14.2                 h2eaa2aa_1    defaults
virtualenv                20.26.3                  pypi_0    pypi
vs2015_runtime            14.29.30133          h43f2093_3    defaults
vtk                       9.4.1                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0            py38haa95532_0    defaults
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0           py38haa95532_0    defaults
widgetsnbextension        4.0.10           py38haa95532_0    defaults
yfinance                  0.2.50                   pypi_0    pypi
zeromq                    4.3.5                hd77b12b_0    defaults
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_1    defaults
zstd                      1.5.5                hd43e919_2    defaults


"""